### ISSUE TITLE
Social widget icons not displaying

### ISSUE THREAD

**Issue by thatgeeman** [AlxMedia/noteblock#1]
Hello, Thanks for the great theme! I'm using WP 5.7.2. When I try to add social widgets on the sidebar, the links and the attributes are present but somehow the [icons won't show](http://gogvg.com/).

**Comment by AlxMedia** [comment]
Hi! Do you have any font awesome/social plugin installed? Try to disable it if so.

To add social links in the theme, try to go to Customize > Theme Options > Social Links > Add New

**Comment by thatgeeman** [comment]
I don't think I have any other fa- plugins installed. But adding links to social profiles via Social Links works. Thanks.
